version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - sony-mathew
  - sojan-official
  - subintp
  labels:
  - dependencies
  - ruby
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.5.1
    - 1.6.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.0
    - 1.88.1
    - 1.89.0
    - 1.90.0
    - 1.91.0
    - 1.92.0
    - 1.93.0
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: telegram-bot-ruby
    versions:
    - 0.14.0
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - pranavrajs
  - nithindavid
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: chart.js
    versions:
    - 2.9.4
    - 3.0.2
    - 3.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: vue-i18n
    versions:
    - 8.22.4
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
